# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'code_review_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeReviewDialog(object):
    def setupUi(self, CodeReviewDialog):
        CodeReviewDialog.setObjectName("CodeReviewDialog")
        CodeReviewDialog.resize(934, 637)
        self.gridLayout = QtWidgets.QGridLayout(CodeReviewDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.solves_list_widget = QtWidgets.QListWidget(CodeReviewDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solves_list_widget.sizePolicy().hasHeightForWidth())
        self.solves_list_widget.setSizePolicy(sizePolicy)
        self.solves_list_widget.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.solves_list_widget.setFont(font)
        self.solves_list_widget.setObjectName("solves_list_widget")
        self.horizontalLayout.addWidget(self.solves_list_widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.code_view = QtWidgets.QTextBrowser(CodeReviewDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.code_view.setFont(font)
        self.code_view.setObjectName("code_view")
        self.verticalLayout.addWidget(self.code_view)
        self.verdict_label = QtWidgets.QLabel(CodeReviewDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verdict_label.setFont(font)
        self.verdict_label.setObjectName("verdict_label")
        self.verticalLayout.addWidget(self.verdict_label)
        self.time_label = QtWidgets.QLabel(CodeReviewDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.verticalLayout.addWidget(self.time_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(CodeReviewDialog)
        QtCore.QMetaObject.connectSlotsByName(CodeReviewDialog)

    def retranslateUi(self, CodeReviewDialog):
        _translate = QtCore.QCoreApplication.translate
        CodeReviewDialog.setWindowTitle(_translate("CodeReviewDialog", "Просмотр предыдущих решений"))
        self.verdict_label.setText(_translate("CodeReviewDialog", "Вердикт"))
        self.time_label.setText(_translate("CodeReviewDialog", "Время выполнения"))
